# Generated by Django 2.2.2 on 2019-08-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190812_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajogroup',
            name='group_member',
        ),
    ]
