# Generated by Django 2.2.2 on 2019-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ajomembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajomembers',
            name='savings',
            field=models.IntegerField(default=0),
        ),
    ]
