# Generated by Django 2.2.2 on 2019-08-16 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_ajomembers_savings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjoGenerator',
            fields=[
                ('Uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='home.AjoGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
